feat: added password change component
FIS2425/frontend pull request #42
Opened 2024-12-31 00:43 UTC by alvgonfri

This pull request introduces a change password component that includes a form to change the password of the logged-in user. This component can be easily added to users' profile pages.

> [!NOTE]  
> To test this you must temporarily include the component on any of the application pages.

2024-12-31 11:07 UTC, AntonioRodriguezRuiz requested changes
Very good overall

2024-12-31 11:07 UTC, AntonioRodriguezRuiz commented on src/forms/auth/schemas.js
> +});
```suggestion
export const changePasswordSchema = z.object({
  currentPassword: z
    .string({ required_error: 'Current password is required' })
    .transform((val) => val.trim()),
  newPassword: z
    .string({ required_error: 'New password is required' })
    .transform((val) => val.trim()),
  confirmPassword: z
    .string({ required_error: 'You need to confirm password' })
    .transform((val) => val.trim()),
}).refine((data) => data.newPassword === data.confirmPassword, {
    message: "Passwords don't match",
    path: ["confirmPassword"],
});

2024-12-31 11:07 UTC, AntonioRodriguezRuiz commented on src/forms/auth/forms.jsx
> +        </Button>
```suggestion
        <FormField
          control={form.control}
          name="newPassword"
          rules={{ required: true }}
          render={({ field }) => (
            <FormItem className="flex flex-col items-start">
              <FormLabel className="text-base font-medium">New Password</FormLabel>
              <FormControl>
                <PasswordInput {...field} />
              </FormControl>
              {form.formState.errors.newPassword && (
                <FormMessage>{form.formState.errors.newPassword.message}</FormMessage>
              )}
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="confirmPassword"
          rules={{ required: true }}
          render={({ field }) => (
            <FormItem className="flex flex-col items-start">
              <FormLabel className="text-base font-medium">Confirm Password</FormLabel>
              <FormControl>
                <PasswordInput {...field} />
              </FormControl>
              {form.formState.errors.confirmPassword && (
                <FormMessage>{form.formState.errors.confirmPassword.message}</FormMessage>
              )}
            </FormItem>
          )}
        />
        <Button className="w-full" type="submit" disabled={isLoading}>
          {isLoading && (
            <LoaderCircle className="mr-2 h-4 w-4 animate-spin" />
          )}
          <span className="text-base font-medium">Update Password</span>
        </Button>
```

2024-12-31 11:07 UTC, AntonioRodriguezRuiz commented on src/components/forms/password-change.jsx
> +    },
```suggestion

    defaultValues: {
      currentPassword: '',
      newPassword: '',
      confirmPassword:'',
},

2024-12-31 11:07 UTC, AntonioRodriguezRuiz commented on src/components/forms/password-change.jsx
> +    changePassword(values)
Here only provide current and new password

2024-12-31 16:44 UTC, alvgonfri commented
Good suggestion!

I added the password confirmation field, but doing so made the dropdown too small for the form, so I changed it to a modal. Making the change to modal has also resolved the problem that did not allow tabulation between form fields.

Tell me if you see it well or do you think we should go back to the dropdown form.

2025-01-02 09:55 UTC, AntonioRodriguezRuiz approved these changes
LGTM

2025-01-02 10:11 UTC, merged